### ISSUE TITLE
custom x/y pixel count

### ISSUE THREAD

**Issue by vindolin** [johncarl81/neopixelplasma#2]
I'm was trying to adapt the code to show a plasma on a single strip but I got weird patterns, the first pixels look like plasma but the rest is rather random.

Can you give me a hint how to tweak the p1/p2/p3 formulas so it looks nice on a 150x neopixel strip?

**Comment by johncarl81** [comment]
I assume you modified the [row](https://github.com/johncarl81/neopixelplasma/blob/master/neopixelplasma.ino#L63) / [col](https://github.com/johncarl81/neopixelplasma/blob/master/neopixelplasma.ino#L67) loops to accommodate your neopixel strip.

You also need to modify the NUM_LED variable to match the number of LEDs you use.

Outside of that you may want to play with the curve calcuation to reach all of your LEDs: https://github.com/johncarl81/neopixelplasma/blob/master/neopixelplasma.ino#L56-L58

Another user was able to adapt this code into a strip of LEDs for a wearable.  Maybe this helps:
https://www.hackster.io/mollycule/wearable-neopixel-sparkle-59ac5d
